export class ErrorCodes {

  static OK = 0;

  static NOT_INITIALISED = -1;

  static COMMAND_INVALID_COMMAND = 10000;
  static COMMAND_MISSING_COMMAND = 10001;
  static COMMAND_MISSING_ARGUMENT = 10002;
  static COMMAND_INVALID_OPTIONS = 10003;

  static CONFIG_MISSING = 20000;

}
